---
- name: trust apt key
  become: yes
  become_user: root
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: install docker.list
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ docker_deb_platform }} main
    state: present
    filename: docker
